# Generated by Django 3.2.7 on 2021-11-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrispyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songs', models.CharField(max_length=500)),
                ('name_of_artist', models.CharField(max_length=500)),
                ('number_of_awards', models.IntegerField()),
            ],
        ),
    ]
